import sys
import os
import time
import logging
import uuid
import json
import urllib.request
import urllib.error
import glob
import re
import argparse

# Configure logging to console
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

LOCAL_API_URL = "http://127.0.0.1:8764/api"

def check_local_api_running():
    try:
        req = urllib.request.Request(f"{LOCAL_API_URL}/ping")
        try:
            urllib.request.urlopen(req, timeout=2)
        except urllib.error.HTTPError as e:
            if e.code == 404:
                return True
            return False
        return True
    except urllib.error.URLError:
        return False

def validate_outcome(doc_id, expected_outcome):
    """
    Validates the actual outcome by reading the flight record JSON files
    generated by AgentStateMachine in client/agent.py.
    """
    if not expected_outcome:
        return True, "No validation criteria specified."

    user_data_dir = os.path.join(os.environ.get("LOCALAPPDATA", ""), "RomyAgentBrowserData", "flight_records", doc_id)
    if not os.path.exists(user_data_dir):
        return False, f"Flight records directory not found: {user_data_dir}"

    record_files = glob.glob(os.path.join(user_data_dir, "record_*.json"))
    if not record_files:
        return False, "No flight records found."

    def get_iteration(filename):
        try:
            return int(os.path.basename(filename).split('_')[1])
        except (IndexError, ValueError):
            return -1

    record_files.sort(key=get_iteration)

    all_actions = []
    all_responses = []
    urls_visited = []

    for file in record_files:
        try:
            with open(file, "r", encoding="utf-8") as f:
                rec = json.load(f)

                # Check for URLs visited
                url = rec.get("prompt_payload", {}).get("current_url", "")
                if url:
                    urls_visited.append(url)

                # Collect all actions taken
                actions = rec.get("action_executed", [])
                if isinstance(actions, list):
                    all_actions.extend(actions)
                elif isinstance(actions, dict):
                    all_actions.append(actions)

                # Collect LLM Responses
                resp = rec.get("llm_response", {})
                all_responses.append(resp)
        except Exception as e:
            logging.error(f"Error reading record file {file}: {e}")

    rule_type = expected_outcome.get("type")

    if rule_type == "os_type_match":
        # Verifies that a specific text was typed into an OS application
        match_str = expected_outcome.get("value", "")
        for act in all_actions:
            if str(act.get("action", "")).upper() == "TYPE":
                # Check if it's an OS environment action
                if match_str.lower() in str(act.get("text", "")).lower():
                    return True, f"Found OS TYPE action containing '{match_str}'"
        return False, f"Never typed '{match_str}' in an OS app. Actions: {all_actions}"

    elif rule_type == "web_type_match":
        # Verifies that specific text was typed on a web page
        match_str = expected_outcome.get("value", "")
        for act in all_actions:
            if str(act.get("action", "")).upper() == "TYPE":
                # Check if it's a WEB environment action
                if match_str.lower() in str(act.get("text", "")).lower():
                    return True, f"Found Web TYPE action containing '{match_str}'"
        return False, f"Never typed '{match_str}' in Web. Actions: {all_actions}"

    elif rule_type == "url_visited":
        match_str = expected_outcome.get("value", "")
        for url in urls_visited:
            if match_str in url:
                return True, f"Visited URL matching '{match_str}'"
        return False, f"Never visited a URL containing '{match_str}'"

    elif rule_type == "reply_match":
        match_str = expected_outcome.get("value", "")
        replies = [str(act.get("text", "")) for act in all_actions if str(act.get("action", "")).upper() == "REPLY"]
        for reply in replies:
            if match_str.lower() in reply.lower():
                return True, f"Reply matched '{match_str}'"
        return False, f"No reply contained '{match_str}'. Replies: {replies}"

    elif rule_type == "memory_injection":
        match_str = expected_outcome.get("value", "")
        for file in record_files:
            try:
                with open(file, "r", encoding="utf-8") as f:
                    rec = json.load(f)
                    prompt_payload = rec.get("prompt_payload", {})
                    client_context = prompt_payload.get("client_context", {})
                    rules = client_context.get("rules", [])

                    if rules:
                        for rule in rules:
                            if match_str.lower() in str(rule).lower():
                                return True, f"Memory rule '{match_str}' found injected in client_context rules."
            except Exception as e:
                pass
        return False, f"Memory rule '{match_str}' was NOT found injected into the context."

    return False, f"Unknown validation rule type: {rule_type}"

def get_scenarios():
    """
    Defines the Phase 5 Systemic Capabilities Test Scenarios.
    """
    return [
        {
            "name": "Web -> Native OS Handoff",
            "command_text": "Extract the current EUR to USD exchange rate from an exchange site (like xe.com or google.com/finance) and write the exact number into the native Windows Notepad app.",
            "client_context": {
                "client_id": "test_phase5_web_to_os",
                "rules": [
                    "Open a new tab to find the exchange rate.",
                    "Once found, open the native Notepad application using the start menu or taskbar.",
                    "Write the exchange rate value directly into the Notepad text area."
                ]
            },
            "expected_outcome": {
                "type": "os_type_match",
                "value": "." # We check if it typed something containing a decimal or number
            }
        },
        {
            "name": "Web -> Stateful Web Handoff",
            "command_text": "Find the current top headline on news.ycombinator.com, copy it, and navigate to a note-taking web app (like google keep or a mock form) and save it as a new note.",
            "client_context": {
                "client_id": "test_phase5_web_to_web",
                "rules": [
                    "Extract the top article title.",
                    "Navigate to a site where you can paste it (e.g. a search engine input or notes app).",
                    "Type the title into a text field and submit."
                ]
            },
            "expected_outcome": {
                "type": "web_type_match",
                "value": " " # Check that it typed a string with spaces (likely a title)
            }
        },
        {
            "name": "Multi-App OS Execution",
            "command_text": "Open the Windows Calculator app. Calculate 15 * 24. Copy the result. Open the Windows Notepad app and write the result into it.",
            "client_context": {
                "client_id": "test_phase5_os_to_os",
                "rules": [
                    "Interact with the Calculator UI elements.",
                    "Extract the text/value from the result display.",
                    "Open Notepad and type the final number."
                ]
            },
            "expected_outcome": {
                "type": "os_type_match",
                "value": "360" # 15 * 24 = 360
            }
        },
        {
            "name": "Active Learning Engine (Memory Injection)",
            "command_text": "Navigate to example.com. Extract the heading.",
            "client_context": {
                "client_id": "test_phase5_memory",
                "rules": [
                    "WISDOM_STRING_INJECTED_MOCK: ALWAYS reply with the word 'BANANA' when extracting headings on example.com."
                ]
            },
            "expected_outcome": {
                "type": "memory_injection",
                "value": "WISDOM_STRING_INJECTED_MOCK"
            }
        }
    ]

def test_harness(run_target=None):
    """
    E2E Test Harness for Phase 5 system capabilities.
    Automatically feeds commands to the agent queue via local API.
    Logs success/failure and execution time of each.
    """
    commands = get_scenarios()

    if run_target is not None:
        try:
            # If target is integer index
            idx = int(run_target) - 1
            if 0 <= idx < len(commands):
                commands = [commands[idx]]
            else:
                print(f"Error: Target index {run_target} out of range.")
                return
        except ValueError:
            # If target is string match
            filtered_commands = [c for c in commands if run_target.lower() in c["name"].lower()]
            if filtered_commands:
                commands = filtered_commands
            else:
                print(f"Error: No scenarios match '{run_target}'.")
                return

    print("=" * 80)
    print("STARTING PHASE 5 CROSS-ENVIRONMENT TEST SUITE")
    print("=" * 80)

    if not check_local_api_running():
        print("ERROR: Local API server is not running on port 8764.")
        print("Please ensure that main.py is running and logged in before executing test_phase5.py")
        return

    results = []

    for i, cmd_obj in enumerate(commands, 1):
        name = cmd_obj["name"]
        cmd = cmd_obj["command_text"]
        expected_outcome = cmd_obj.get("expected_outcome")
        client_context = cmd_obj.get("client_context")
        doc_id = f"phase5_test_run_{uuid.uuid4().hex[:8]}"
        rule_type = expected_outcome.get("type", "") if expected_outcome else ""

        print(f"\n[{i}/{len(commands)}] Running Scenario: {name}")
        print(f"Command: {cmd}")
        print(f"Tracking session ID: {doc_id}")

        start_time = time.time()
        status = "failed (initialization)"
        elapsed = 0

        try:
            # Enqueue the command via local API
            payload_dict = {
                "doc_id": doc_id,
                "command_text": cmd
            }
            if client_context:
                payload_dict["client_context"] = client_context

            payload = json.dumps(payload_dict).encode('utf-8')

            req = urllib.request.Request(f"{LOCAL_API_URL}/run_command", data=payload, headers={'Content-Type': 'application/json'}, method='POST')
            response = urllib.request.urlopen(req)
            resp_data = json.loads(response.read().decode())

            if resp_data.get("status") != "queued":
                print(f"Failed to queue command. API returned: {resp_data}")
                status = "failed (queue error)"
            else:
                # Wait for the task to finish by polling status
                status = "pending"
                while status not in ["completed", "failed"]:
                    time.sleep(2)
                    try:
                        status_req = urllib.request.Request(f"{LOCAL_API_URL}/status/{doc_id}")
                        status_response = urllib.request.urlopen(status_req)
                        status_data = json.loads(status_response.read().decode())
                        status = status_data.get("status", "unknown")
                        if status == "AWAITING_HUMAN_INPUT":
                            print("HITL Deadlock detected in automated test. Failing scenario immediately.")
                            status = "failed (HITL deadlock)"
                            break
                    except Exception as e:
                        print(f"Failed to get status. Error: {e}")
                        status = "failed (status poll error)"
                        break
        except Exception as e:
            print(f"Exception during scenario execution: {e}")
            status = f"failed (exception: {e})"

        end_time = time.time()
        elapsed = end_time - start_time

        # Validation step
        validation_passed = False
        validation_reason = ""

        # Memory injection scenario doesn't require the command to 'complete' execution perfectly,
        # it just needs to be injected. We validate either on completion or if it's a memory rule.
        if status == "completed" or rule_type == "memory_injection":
            validation_passed, validation_reason = validate_outcome(doc_id, expected_outcome)
            if not validation_passed:
                status = f"failed (validation: {validation_reason})"
            elif status != "completed":
                status = "completed"

        print(f"-> Scenario finished in {elapsed:.2f} seconds. Final Status: {status}")
        if validation_reason:
            print(f"Validation: {validation_reason}")

        results.append({
            "name": name,
            "command": cmd,
            "elapsed": elapsed,
            "status": status
        })

        # Give the system a brief moment before the next test
        time.sleep(2)

    print("\n" + "=" * 80)
    print("PHASE 5 TEST SUITE SUMMARY MATRIX")
    print("=" * 80)
    print(f"{'SCENARIO':<60} | {'STATUS':<15} | {'TIME'}")
    print("-" * 80)
    for res in results:
        name_trunc = res['name'][:57] + "..." if len(res['name']) > 60 else res['name']
        print(f"{name_trunc:<60} | {res['status']:<15} | {res['elapsed']:.2f}s")
    print("=" * 80)

    success_count = sum(1 for r in results if r['status'] == 'completed')
    total_count = len(results)
    print(f"Total Passed: {success_count} / {total_count}")
    print("=" * 80)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run Phase 5 Systemic Tests via Local API.")
    parser.add_argument("--run", type=str, help="Index or partial name of the scenario to run.")
    args = parser.parse_args()

    print("Note: Make sure your desktop client (main.py) is actively running and logged in.")
    test_harness(run_target=args.run)
